[package]
name = "handyman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
color-eyre = "0.6.2"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
which = "4.4.0"

[dev-dependencies]
tempfile = "3.3.0"
